/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliverycervejas;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.util.Arrays;


/**
 *
 * @author thiag
 */
public class CadastroUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form tela1
     */
    public CadastroUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomeUsuario = new javax.swing.JTextField();
        enderecoUsuario = new javax.swing.JTextField();
        cidadeUsuario = new javax.swing.JTextField();
        rgUsuario = new javax.swing.JTextField();
        cpfUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        telefoneUsuario = new javax.swing.JTextField();
        cepUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ufUsuario = new javax.swing.JComboBox<>();
        numeroUsuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailUsuario = new javax.swing.JTextField();
        loginUsuario = new javax.swing.JTextField();
        cadastrar = new java.awt.Button();
        cancelar = new java.awt.Button();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        imagembeer = new javax.swing.JLabel();
        dataUsuario = new javax.swing.JFormattedTextField();
        senhaUsuario = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(102, 153, 0));
        jLabel1.setText("Usuário");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(80, 360, 50, 30);

        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Nome");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 110, 40, 30);

        jLabel3.setForeground(new java.awt.Color(102, 153, 0));
        jLabel3.setText("Data de Nascimento");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(610, 110, 100, 30);

        jLabel4.setForeground(new java.awt.Color(102, 153, 0));
        jLabel4.setText("Nº");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 240, 20, 30);

        jLabel5.setForeground(new java.awt.Color(102, 153, 0));
        jLabel5.setText("RG");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(260, 180, 33, 30);

        jLabel6.setForeground(new java.awt.Color(102, 153, 0));
        jLabel6.setText("Endereço");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(440, 180, 80, 30);

        nomeUsuario.setBackground(new java.awt.Color(51, 102, 0));
        nomeUsuario.setToolTipText("");
        jPanel2.add(nomeUsuario);
        nomeUsuario.setBounds(130, 110, 460, 37);

        enderecoUsuario.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.add(enderecoUsuario);
        enderecoUsuario.setBounds(490, 180, 330, 37);

        cidadeUsuario.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.add(cidadeUsuario);
        cidadeUsuario.setBounds(490, 240, 230, 37);

        rgUsuario.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.add(rgUsuario);
        rgUsuario.setBounds(280, 180, 150, 37);

        cpfUsuario.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.add(cpfUsuario);
        cpfUsuario.setBounds(130, 180, 120, 37);

        jLabel7.setForeground(new java.awt.Color(102, 153, 0));
        jLabel7.setText("CPF");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(90, 180, 28, 30);

        jLabel8.setForeground(new java.awt.Color(102, 153, 0));
        jLabel8.setText("CEP");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(260, 240, 28, 30);

        jLabel9.setForeground(new java.awt.Color(102, 153, 0));
        jLabel9.setText("Cidade");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(450, 240, 40, 30);

        telefoneUsuario.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.add(telefoneUsuario);
        telefoneUsuario.setBounds(490, 300, 230, 37);

        cepUsuario.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.add(cepUsuario);
        cepUsuario.setBounds(280, 240, 150, 37);

        jLabel10.setForeground(new java.awt.Color(102, 153, 0));
        jLabel10.setText("UF");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(730, 240, 20, 30);

        jLabel11.setForeground(new java.awt.Color(102, 153, 0));
        jLabel11.setText("Telefone");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(440, 300, 50, 30);

        jLabel12.setForeground(new java.awt.Color(102, 153, 0));
        jLabel12.setText("E-mail");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(80, 300, 50, 30);

        ufUsuario.setBackground(new java.awt.Color(51, 102, 0));
        ufUsuario.setEditable(true);
        ufUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", " DF", "ES", "GO", "MA", "MT", "MS", " MG", " PA", " PB", " PR", " PE", " PI", " RJ", " RN", " RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel2.add(ufUsuario);
        ufUsuario.setBounds(750, 240, 70, 40);

        numeroUsuario.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.add(numeroUsuario);
        numeroUsuario.setBounds(130, 240, 120, 37);

        jLabel13.setForeground(new java.awt.Color(102, 153, 0));
        jLabel13.setText("Senha");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(450, 360, 40, 30);

        emailUsuario.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.add(emailUsuario);
        emailUsuario.setBounds(130, 300, 300, 37);

        loginUsuario.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.add(loginUsuario);
        loginUsuario.setBounds(130, 360, 300, 37);

        cadastrar.setBackground(new java.awt.Color(239, 239, 0));
        cadastrar.setLabel("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(cadastrar);
        cadastrar.setBounds(250, 440, 120, 60);

        cancelar.setBackground(new java.awt.Color(239, 239, 0));
        cancelar.setLabel("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel2.add(cancelar);
        cancelar.setBounds(540, 440, 120, 60);

        jLabel15.setText("jLabel15");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(30, 30, 38, 13);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverycervejas/pngwing.com555 (5).png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(0, -40, 620, 220);

        imagembeer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverycervejas/pngwing.com (3).png"))); // NOI18N
        imagembeer.setText("jLabel16");
        jPanel2.add(imagembeer);
        imagembeer.setBounds(740, 330, 140, 170);

        dataUsuario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jPanel2.add(dataUsuario);
        dataUsuario.setBounds(710, 110, 110, 40);

        senhaUsuario.setBackground(new java.awt.Color(51, 102, 0));
        jPanel2.add(senhaUsuario);
        senhaUsuario.setBounds(490, 360, 230, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        String email = this.emailUsuario.getText();
        String nome = this.nomeUsuario.getText();
        String cpf = this.cpfUsuario.getText();
        String rg = this.rgUsuario.getText();
        String endereco = this.enderecoUsuario.getText();
        String numero = this.numeroUsuario.getText();
        String cep = this.cepUsuario.getText();
        String cidade = this.cidadeUsuario.getText();
        String uf = this.ufUsuario.getSelectedItem().toString();
        String telefone = this.telefoneUsuario.getText();
        String login = this.loginUsuario.getText();
        String senha = String.valueOf(this.senhaUsuario.getPassword());
        String data = this.dataUsuario.getText();

        Conexao conexao = new Conexao();
        try {
            Connection con = conexao.getConexao();
            String sql = "INSERT INTO usuario (nome,nascimento,cpf,rg,endereco,numero,cep,cidade,uf,email,telefone,login,senha)"
                    + " VALUES ( ?,?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, nome);
            statement.setString(2, data);
            statement.setString(3, cpf);
            statement.setString(4, rg);
            statement.setString(5, endereco);
            statement.setString(6,numero);
            statement.setString(7,cep);
            statement.setString(8,cidade);
            statement.setString(9,uf);
            statement.setString(10,email);
            statement.setString(11,telefone);
            statement.setString(12,login);
            statement.setString(13,senha);
                   

            int rowsInserted = statement.executeUpdate();
            con.close();
            if (rowsInserted > 0) {
              JOptionPane.showMessageDialog(this, "Cadastro efetuado com sucesso.");
              this.setVisible(false);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

        

    }//GEN-LAST:event_cadastrarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.setVisible(false);

    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button cadastrar;
    private java.awt.Button cancelar;
    private javax.swing.JTextField cepUsuario;
    private javax.swing.JTextField cidadeUsuario;
    private javax.swing.JTextField cpfUsuario;
    private javax.swing.JFormattedTextField dataUsuario;
    private javax.swing.JTextField emailUsuario;
    private javax.swing.JTextField enderecoUsuario;
    private javax.swing.JLabel imagembeer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField loginUsuario;
    private javax.swing.JTextField nomeUsuario;
    private javax.swing.JTextField numeroUsuario;
    private javax.swing.JTextField rgUsuario;
    private javax.swing.JPasswordField senhaUsuario;
    private javax.swing.JTextField telefoneUsuario;
    private javax.swing.JComboBox<String> ufUsuario;
    // End of variables declaration//GEN-END:variables
}
