/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliverycervejas;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author thiag
 */
public class MenuCervejas extends javax.swing.JFrame {
    HashMap usuarioMap;
    /**
     * Creates new form tela3
     */
    public MenuCervejas() {
        initComponents();
    }
    
    public MenuCervejas (HashMap map) {
        initComponents();
        this.usuarioMap = map; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        laTrappe = new javax.swing.JSpinner();
        adicionarCerveja = new java.awt.Button();
        duvel = new javax.swing.JSpinner();
        punkIpa = new javax.swing.JSpinner();
        samuelAdams = new javax.swing.JSpinner();
        erdinger = new javax.swing.JSpinner();
        guinnessExtraStout = new javax.swing.JSpinner();
        guinness = new javax.swing.JSpinner();
        paulaner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverycervejas/duvel (9).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 40, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverycervejas/erdinger (5).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 510, 80, 170);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverycervejas/guinness stout (2).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 30, 70, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverycervejas/la trappe (8).png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 520, 60, 160);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverycervejas/paulaner (7).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(460, 360, 60, 150);

        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(590, 310, 33, 13);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverycervejas/pguinness (1).png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 200, 60, 130);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverycervejas/punk ipa (4).png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 190, 50, 150);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverycervejas/samuel adams (10).png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 350, 110, 160);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 153, 0));
        jLabel11.setText("-  R$21,90");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 670, 110, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 153, 0));
        jLabel12.setText("-  Belgian Strong Ale");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(100, 60, 200, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 153, 0));
        jLabel13.setText("-  Bélgica");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(100, 90, 100, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 153, 0));
        jLabel14.setText("-  8,5%");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(100, 120, 80, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 153, 0));
        jLabel15.setText("-  R$20,99");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(100, 150, 110, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 153, 0));
        jLabel16.setText("-  Punk Ipa");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(100, 210, 110, 22);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 153, 0));
        jLabel17.setText("-  IPA");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(100, 240, 110, 22);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 153, 0));
        jLabel18.setText("-  Escócia");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(100, 270, 110, 22);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 153, 0));
        jLabel19.setText("-  5,6%");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(100, 300, 110, 22);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 153, 0));
        jLabel20.setText("-  R$18,99");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(100, 330, 110, 22);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 153, 0));
        jLabel21.setText("-  R$18,99");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(100, 330, 110, 22);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 153, 0));
        jLabel22.setText("-  Samuel Adams");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(100, 380, 160, 22);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 153, 0));
        jLabel23.setText("-  Boston Lager");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(100, 410, 150, 22);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 153, 0));
        jLabel24.setText("-  Estados Unidos");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(100, 440, 170, 22);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 153, 0));
        jLabel25.setText("-  5,7%");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(100, 470, 110, 22);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 153, 0));
        jLabel26.setText("-  R$17,90");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(100, 500, 110, 22);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 153, 0));
        jLabel27.setText("-  Erdinger");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(100, 550, 110, 22);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 153, 0));
        jLabel28.setText("-  Weiss");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(100, 580, 110, 22);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 153, 0));
        jLabel29.setText("-  Alemanha");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(100, 610, 110, 22);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 153, 0));
        jLabel30.setText("-  5,3%");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(100, 640, 110, 22);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 153, 0));
        jLabel31.setText("-  Duvel");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(100, 40, 80, 13);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 153, 0));
        jLabel32.setText("-  R$45,00");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(530, 150, 100, 22);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 153, 0));
        jLabel33.setText("-  R$31,90");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(530, 670, 100, 22);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 153, 0));
        jLabel34.setText("-  Stout");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(530, 60, 80, 22);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 153, 0));
        jLabel35.setText("-  Irlanda");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(530, 90, 80, 22);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 153, 0));
        jLabel36.setText("-  6,5%");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(530, 120, 80, 22);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 153, 0));
        jLabel37.setText("-  Guinness Extra Stout");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(530, 31, 220, 22);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 153, 0));
        jLabel38.setText("-  Guinness ");
        jPanel1.add(jLabel38);
        jLabel38.setBounds(530, 200, 220, 22);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 153, 0));
        jLabel39.setText("-  Dry Stout");
        jPanel1.add(jLabel39);
        jLabel39.setBounds(530, 230, 220, 22);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 153, 0));
        jLabel40.setText("-  Irlanda");
        jPanel1.add(jLabel40);
        jLabel40.setBounds(530, 260, 220, 22);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 153, 0));
        jLabel41.setText("-  4,1%");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(530, 290, 90, 22);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(102, 153, 0));
        jLabel42.setText("-  R$17,90");
        jPanel1.add(jLabel42);
        jLabel42.setBounds(530, 320, 110, 22);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 153, 0));
        jLabel43.setText("-  Paulaner");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(530, 370, 220, 22);

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 153, 0));
        jLabel44.setText("-  Weiss");
        jPanel1.add(jLabel44);
        jLabel44.setBounds(530, 400, 220, 22);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 153, 0));
        jLabel45.setText("-  Alemanha");
        jPanel1.add(jLabel45);
        jLabel45.setBounds(530, 430, 220, 22);

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 153, 0));
        jLabel46.setText("-  5,5%");
        jPanel1.add(jLabel46);
        jLabel46.setBounds(530, 460, 110, 22);

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 153, 0));
        jLabel47.setText("-  R$19,99");
        jPanel1.add(jLabel47);
        jLabel47.setBounds(530, 490, 100, 22);

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 153, 0));
        jLabel48.setText("-  La Trappe Triple");
        jPanel1.add(jLabel48);
        jLabel48.setBounds(530, 550, 220, 22);

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(102, 153, 0));
        jLabel49.setText("-  Belgian Pale Ale");
        jPanel1.add(jLabel49);
        jLabel49.setBounds(530, 580, 220, 22);

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(102, 153, 0));
        jLabel50.setText("-  Holanda");
        jPanel1.add(jLabel50);
        jLabel50.setBounds(530, 610, 220, 22);

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(102, 153, 0));
        jLabel51.setText("-  8,00%");
        jPanel1.add(jLabel51);
        jLabel51.setBounds(530, 640, 100, 22);

        laTrappe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(laTrappe);
        laTrappe.setBounds(640, 640, 60, 40);

        adicionarCerveja.setBackground(new java.awt.Color(216, 216, 21));
        adicionarCerveja.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        adicionarCerveja.setLabel("Adicionar");
        adicionarCerveja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCervejaActionPerformed(evt);
            }
        });
        jPanel1.add(adicionarCerveja);
        adicionarCerveja.setBounds(320, 710, 200, 70);

        duvel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(duvel);
        duvel.setBounds(220, 120, 60, 40);

        punkIpa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(punkIpa);
        punkIpa.setBounds(220, 280, 60, 40);

        samuelAdams.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(samuelAdams);
        samuelAdams.setBounds(210, 470, 60, 40);

        erdinger.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(erdinger);
        erdinger.setBounds(220, 640, 60, 40);

        guinnessExtraStout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(guinnessExtraStout);
        guinnessExtraStout.setBounds(630, 120, 60, 40);

        guinness.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(guinness);
        guinness.setBounds(630, 280, 60, 40);

        paulaner.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(paulaner);
        paulaner.setBounds(630, 470, 60, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarCervejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCervejaActionPerformed
        int duvelNome = (int) duvel.getValue();
        int paulanerNome = (int) paulaner.getValue();
        int guinnessNome = (int) guinness.getValue();
        int guinnessExtraNome = (int) guinnessExtraStout.getValue();
        int erdingerNome = (int) erdinger.getValue();
        int punkIpaNome = (int) punkIpa.getValue();
        int samuelAdamsNome = (int) samuelAdams.getValue();
        int laTrappeNome = (int) laTrappe.getValue();

        Map map = new HashMap();
        // Put elements to the map
        map.put("duvel", duvelNome);
        map.put("paulaner", paulanerNome);
        map.put("guinness", guinnessNome);
        map.put("guinnessExtraStout", guinnessExtraNome);
        map.put("erdinger",erdingerNome);
        map.put("punkIpa",punkIpaNome);
        map.put("samuelAdams",samuelAdamsNome);
        map.put("laTrappe",laTrappeNome);
        map.put("usuario",this.usuarioMap.get("usuario"));
        map.put("nome",this.usuarioMap.get("nome"));
        map.put("id",this.usuarioMap.get("id"));
        
        

        Pagamento pagamento = new Pagamento((HashMap) map);
        pagamento.setVisible(true);
        
    }//GEN-LAST:event_adicionarCervejaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCervejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCervejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCervejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCervejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCervejas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button adicionarCerveja;
    private javax.swing.JSpinner duvel;
    private javax.swing.JSpinner erdinger;
    private javax.swing.JSpinner guinness;
    private javax.swing.JSpinner guinnessExtraStout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner laTrappe;
    private javax.swing.JSpinner paulaner;
    private javax.swing.JSpinner punkIpa;
    private javax.swing.JSpinner samuelAdams;
    // End of variables declaration//GEN-END:variables
}
